services:
  nuxt:
    container_name: nuxt-app
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; 
             while :; do 
               certbot renew --webroot -w /var/www/certbot && nginx -s reload; 
               sleep 12h & wait $${!}; 
             done"
    restart: unless-stopped

volumes:
  certs:
  certbot-www:
