name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CR_URI: zabastx.cr.cloud.ru
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CR_URI }}
          username: ${{ secrets.EVO_CR_LOGIN }}
          password: ${{ secrets.EVO_CR_PWD }}
          
      - name: Nuxt App
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.CR_URI }}/task-manager:${{ github.sha }}
          file: ./Dockerfile
          context: ./
